variables:
- group: common

- name: cacheVolumes
  value: |
    /opt/cache/node_modules/adaptive_cards:/source/node_modules

pool: 'Digital'

steps:
- task: DockerAdvanced@0
  displayName: 'COMMIT_install'
  inputs:
    image: 'registry.see.asseco.com/tools/angular-module-builder:9.0'
    dockerRegistryEndpoint: harbor
    secureFile: npm-asee-dp-robot
    commands: |
      cp npm-asee-dp-robot /root/.npmrc   
      npm install --no-progress --loglevel=warn
      vsce package
    volumes: |
      $(cacheVolumes)